Algoritmo "operadoresrelacionais"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/08/2021
Var
// Seção de Declarações das variáveis 
   nota1, nota2: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   nota1 := 10
   nota2 := 15
   
   se (nota1 <> nota2) entao
      escreval ("nota 1 é diferente")
   senao
      escreval ("nota 1 é igual")
   fimse

Fimalgoritmo